fix(AgGridAdapter): rewrite styles, tools and components
consta-design-system/ag-grid-adapter pull request #26
Opened 2023-06-20 11:20 UTC by N1MBER

closes consta-design-system/uikit#3043

2023-07-12 12:27 UTC, gizeasy commented
![image](https://github.com/consta-design-system/ag-grid-adapter/assets/13190808/05f308a0-d548-4fbf-acfc-43cd7c593fd2)

при включение вертикальных бордеров, имеют скругление

2023-07-12 12:28 UTC, gizeasy commented
не корректно отробатывает выравнивание в ячейках

2023-07-12 12:28 UTC, gizeasy commented
'загаловке' опечатка

2023-07-12 12:29 UTC, gizeasy commented
![image](https://github.com/consta-design-system/ag-grid-adapter/assets/13190808/e8cc6338-5c2c-42bd-9e7c-20e928a028b4)

скукожился радиобатон

2023-07-12 12:30 UTC, gizeasy commented
![image](https://github.com/consta-design-system/ag-grid-adapter/assets/13190808/fab4ca20-7d8e-4fee-bff8-761e6dbc8e73)

развалился чекбокс

2023-07-12 12:32 UTC, gizeasy commented
![image](https://github.com/consta-design-system/ag-grid-adapter/assets/13190808/9066468d-ab39-4140-9933-8fa8a9544362)

точки другого цвета

2023-07-12 12:34 UTC, gizeasy commented
![image](https://github.com/consta-design-system/ag-grid-adapter/assets/13190808/e4fb1819-1333-4fba-bc7c-9070ec75497e)

добавить ховер эфект

2023-07-26 12:10 UTC, gizeasy commented
Ждем лешу с фильрами в разных размерностях
и pivotMode

2023-08-30 15:52 UTC, BagenovA requested changes

2023-08-30 15:52 UTC, BagenovA commented on src/adapters/agGridAdapter/AgGridAdapter.css
> +  src: url(data:font/woff2;charset=utf-8;base64,d09GMgABAAAAABIkAAsAAAAAJkAAABHTAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIkABmAAiyoKp0ygSgE2AiQDgjALgRoABCAFhEYHhRwbXyFFIbBxAJDYv7AiqieV7P96QZO4Gu9qEMLAgorXqyj
Это пароль от почты Пентагона?

2023-08-30 15:52 UTC, BagenovA commented on src/adapters/agGridAdapter/__stand__/examples/AgGridAdapterExampleBasic/AgGridAdapterExampleBasic.tsx
> +    { user: 'Шапокляк', role: 'вредитель', приорpriorityитет: '777' },
Разделить "приоритет" и priority

2023-08-30 15:52 UTC, BagenovA commented on src/stand/standConfig.ts
>      'Адптер для библиотеки ag-grid-react. Стилизует таблицу для дизайн-системы Consta.',
Исправить опечатку в слове "адаптер"

2023-09-06 16:31 UTC, N1MBER commented on src/adapters/agGridAdapter/AgGridAdapter.css
> +  src: url(data:font/woff2;charset=utf-8;base64,d09GMgABAAAAABIkAAsAAAAAJkAAABHTAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIkABmAAiyoKp0ygSgE2AiQDgjALgRoABCAFhEYHhRwbXyFFIbBxAJDYv7AiqieV7P96QZO4Gu9qEMLAgorXqyj
Это шрифт в формате base64)

2023-09-25 08:59 UTC, gizeasy requested changes
![image](https://github.com/consta-design-system/ag-grid-adapter/assets/13190808/471731f5-e03f-4624-bb64-0c776c4f19d1)

список не в цвете темы
тут нашел

https://refs-pull-26-merge---ag-grid-adapter.consta.design/libs/ag-grid-adapter/components-dateinput-stable

2023-09-27 14:05 UTC, merged